[package]
name = "server"
version = "0.1.0"
authors = ["Your Name <email@address.com>"]
edition = "2018"

[dependencies]
actix = "0.9.0"
actix-web = "2.0.0"
actix-rt = "1"
actix-files = "0.2.1"
actix-multipart = "0.2.0"
actix-session = "0.3.0"
tokio-timer = "0.2.13"
get_if_addrs = "0.5.3"
failure = "0.1.6"
jfs = "0.6.2"
serde = { version = "1.0.104", features = ["derive"]}
ipnet = { version = "2.2", features = ["serde"] }
tempfile = "3.1.0"
bcrypt = "0.6"

shared = { path = "../shared" }
