[package]
name = "server"
version = "0.1.0"
authors = ["Your Name <email@address.com>"]
edition = "2018"

[dependencies]
actix = "0.9.0"
actix-web = "2.0.0"
actix-rt = "1.1.1"
actix-files = "0.2.2"
actix-multipart = "0.2.0"
tokio-timer = "0.2.13"
get_if_addrs = "0.5.3"
actix-identity = "0.2.1"
actix-http = "1.0.1"
failure = "0.1.8"
jfs = "0.6.2"
serde = { version = "1.0.115", features = ["derive"]}
ipnet = { version = "2.3", features = ["serde"] }
tempfile = "3.1.0"
bcrypt = "0.8"

shared = { path = "../shared" }
